# Jekyll configuration for GitHub Pages
title: "Carpet PvP Documentation"
description: "Complete documentation for Carpet PvP mod - features, commands, and configuration"
url: "https://andrewctf.github.io"
baseurl: "/Carpet-PvP"

# Theme configuration
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Search functionality
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Navigation
nav_sort: case_insensitive
nav_external_links:
  - title: "GitHub Repository"
    url: "https://github.com/AndrewCTF/Carpet-PvP"
  - title: "Modrinth Page"
    url: "https://modrinth.com/mod/carpet-pvp-(updates)"

# Footer
footer_content: "Copyright &copy; 2025 AndrewCTF. Distributed under the MIT License."

# GitHub Pages and plugins
plugins:
  - jekyll-default-layout
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Exclude files
exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile
  - docs/tests/

# Collections for organized content
collections:
  commands:
    permalink: "/:collection/:name/"
    output: true
  rules:
    permalink: "/:collection/:name/"
    output: true
  features:
    permalink: "/:collection/:name/"
    output: true

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_commands"
    values:
      layout: default
      parent: Commands
  - scope:
      path: "_rules" 
    values:
      layout: default
      parent: Rules
  - scope:
      path: "_features"
    values:
      layout: default
      parent: Features
